import Head from 'next/head'
import Layout from '../public/components/layout'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Kaio Vinicius</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Layout />

    </div>
  )
}