import Head from 'next/head'
import Navbar from '../public/components/navbar'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { ImLinkedin2 } from 'react-icons/im'
import { VscGithubAlt } from 'react-icons/vsc'
import Sobre from '../public/components/sobre'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>

        <section className={styles.box}>
          <div className={styles.boxText}>
            <h1>Olá, eu sou o Kaio Vinicius seja bem-vindo(a)</h1>
            <p>Desenvolvedor Front-End</p>
            <br />
            <a href='#' data-Linkedin><ImLinkedin2 /> Linkedin</a>
            <a href='#' data-Github> <VscGithubAlt /> Github</a>
          </div>

          <div className={styles.img}>
            <Image
              src="/img/soft1.svg"
              alt="Picture"
              width={550}
              height={450}
            />
          </div>
        </section>

        <section>
          <div id="Sobre">
            <Sobre/>
          </div>
        </section>
      </main>

      <footer>

      </footer>

    </div>
  )
}
